### ISSUE TITLE
Interface does not load

### ISSUE THREAD

**Issue by morhi** [directus/example-interface-stock#1]
I tried to create a new custom interface and followed the instructions in the ReadMe. However, when I want to use the custom interface in a new field the form _only displays a spinner_ and does not show the actual interface. I also tried it with the simplest markup and script possible but it still does not load. The loading process of the custom files itself works, if I copy files from a core interface.

Could you try to reproduce the issue? I used Node v10 and v11 on Mac OS X.

Edit: There are no errors in the JavaScript console and I did not find a way to debug the issue yet.

**Comment by benhaynes** [comment]
@rijkvanzanten — any thoughts on this?

**Comment by gabormeszoly** [comment]
@morhi find here `Settings > Interfaces > Stock`

![Screen Shot 2019-04-18 at 15 08 57](https://user-images.githubusercontent.com/1769854/56363251-112f4f00-61ec-11e9-8626-4ce121acf962.png)

**Comment by kateerogers** [comment]
I am also seeing this issue with this test repo. Is there any additional documentation to help us get a test custom extension running?

**Comment by ThomasKliszowski** [comment]
If I try to build this Interface and open the debug page @gabormeszoly has, here is the error I get:
![image](https://user-images.githubusercontent.com/1174135/56742021-48fe3f80-6774-11e9-96eb-7adcf8ea24a9.png)

**Comment by benhaynes** [comment]
@rijkvanzanten — let's review this and ensure it's building/working as expected.

**Comment by rijkvanzanten** [comment]
Yeah I think I know what's causing it. I'll update the repo to use the new extension builder ASAP

**Comment by rijkvanzanten** [comment]
Updated the package.json file. Should be all good now.
